<fieldset class="form-list">
	<?php $_code=$this->getMethodCode(); ?>
	<ul id="payment_form_<?php echo $_code ?>" style="display:none">
		<?php
			$model = $this->getMethod();
			$model->startOrderCapture();
		?>
	 	<li>
			<label for="<?php echo $_code ?>_number" class="required"><em>*</em><?php echo $this->__('Card Number') ?></label>
			<div class="input-box">
				<input type="text" id="<?php echo $_code ?>_number" name="payment[cardNumber]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Number')) ?>" class="input-text validate-cc-number validate-cc-type required-entry" placeholder="Card Number" value="" />
			</div>
		</li>
		<li>
			<label class="required" for="<?php echo $_code ?>_expirymonth"><em>*</em>Expiration Date</label>
			<div class="input-box">
				<div class="v-fix">
					<input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Card expiry month')) ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_expirymonth" name="payment[cardExpiryMonth]" placeholder="MM" maxlength="2" value="" />
				</div>
				<input type="text" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Card expiry year')) ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_expiryyear" name="payment[cardExpiryYear]" maxlength="2" placeholder="YY" value="" />
			</div>
		</li>
	<li>
		<label for="<?php echo $_code ?>_cvv" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
		<div class="input-box">
			<div class="v-fix">
				<input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Verification Number')) ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cvv" name="payment[cardCVV]" maxlength="4" placeholder="CVV" value="" />
			</div>
			<a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
			<br/>
		</div>
		<br/>
		<p><?php echo $this->getMethod()->getConfigData('message');?></p>
	</li>
	</ul>
</fieldset>
