<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Cardstream_CardstreamHosted
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-title">
    <h2 style="color:red;"><?php echo $this->__('Your payment has either been declined or has failed') ?></h2>
</div>
<p><?php echo $this->__('Declined/Failed transactions occur for various reasons, the most common being insufficient funds, incorrect card information, expired card or AVS/CV2 mismatch.') ?></p>
<p><?php echo $this->__('In rare cases there may be a communication error or technical problem. If your card continues to be declined, please contact your bank before contacting us.') ?></p>
<p><?php echo $this->__('Alternatively you may wish to use a alternative method of payment.') ?></p>
<p><a href="<?php echo Mage::getUrl('checkout/cart') ?>"><?php echo $this->__('Retry Payment') ?></a>
